Add a github actions CI system
NUbots/dashboard pull request #4
Opened 2021-03-22 06:27 UTC by TrentHouliston

2021-03-22 07:16 UTC, Bidski commented
You and your github actions @TrentHouliston !!

2021-03-22 09:45 UTC, JosephusPaye commented
I know right 😅

2021-03-22 10:02 UTC, JosephusPaye requested changes, later dismissed
How can I say no to free work that's already done? 😛

2021-03-22 10:02 UTC, JosephusPaye commented on .github/workflows/main.yaml
> +    container: node:12
We can probably bump to Node 14, the latest LTS.

2021-03-22 10:06 UTC, JosephusPaye commented
Also, does the caching `yarn` actually work? I remember we had issues with Horus.

2021-03-22 13:49 UTC, TrentHouliston commented
That environment variable doesn't actually do caching, it just sets it to a folder so it works properly. Since it's in the cloud you can probably do the cache in a future PR

2021-03-22 21:53 UTC, Bidski requested changes

2021-03-22 21:53 UTC, Bidski commented on .github/workflows/main.yaml
> +    # Run on the Node 12 container
```suggestion
    # Run on the Node 14 container
```

2021-03-22 21:53 UTC, Bidski commented on .github/workflows/main.yaml
> +    container: node:12
```suggestion
    # Run on the Node 14 container
    container: node:14
```

2021-03-22 21:53 UTC, Bidski commented on .github/workflows/main.yaml
> +    container: node:12
```suggestion
    # Run on the Node 14 container
    container: node:14
```

2021-03-22 21:53 UTC, Bidski commented on .github/workflows/main.yaml
> +    container: node:12
```suggestion
    # Run on the Node 14 container
    container: node:14
```

2021-03-22 23:21 UTC, Bidski approved these changes
Looks ok, now you just need to figure out why the checks are failing!

2021-03-23 00:06 UTC, JosephusPaye commented
Tests are failing due to the missing proto messages, which is fixed in #3.

2021-03-23 03:36 UTC, JosephusPaye approved these changes
LGTM

2021-03-23 03:39 UTC, merged